### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)

### ISSUE THREAD

**Issue by ranezu** [aajanki/yle-dl#154]
First things first: thank you very much for this great tool!

I may have discovered a minor bug. If filename is given with the -o flag and it contains non-ascii characters, the file can not be downloaded at all.
```
$ yle-dl -o ääkkönen.mp4 https://areena.yle.fi/1-2980036
/home/sami/.local/lib/python2.7/site-packages/yledl/yledl.py:336: UnicodeWarning: Unicode equal comparison failed to convert both arguments to Unicode - interpreting them as being unequal
  elif args.pipe or (args.outputfile == '-'):
yle-dl 2.31: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2018 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3
Traceback (most recent call last):
  File "/usr/local/bin/yle-dl", line 11, in <module>
    sys.exit(main())
  File "/home/sami/.local/lib/python2.7/site-packages/yledl/yledl.py", line 366, in main
    args.postprocess)
  File "/home/sami/.local/lib/python2.7/site-packages/yledl/yledl.py", line 234, in download
    postprocess_command)
  File "/home/sami/.local/lib/python2.7/site-packages/yledl/downloaders.py", line 993, in download_episodes
    return self.process(download_clip, url, filters)
  File "/home/sami/.local/lib/python2.7/site-packages/yledl/downloaders.py", line 1040, in process
    res = self.process_single_episode(clipfunc, clipurl, filters)
  File "/home/sami/.local/lib/python2.7/site-packages/yledl/downloaders.py", line 1143, in process_single_episode
    res = clipfunc(clip)
  File "/home/sami/.local/lib/python2.7/site-packages/yledl/downloaders.py", line 985, in download_clip
    self.download_subtitles(selected_subtitles, outputfile)
  File "/home/sami/.local/lib/python2.7/site-packages/yledl/downloaders.py", line 405, in download_subtitles
    filename = basename + '.' + sub.language + '.srt'
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 0: ordinal not in range(128)
```
Locale:
```
$ locale
LANG=fi_FI.UTF-8
LANGUAGE=en_US:en
LC_CTYPE=fi_FI.UTF-8
LC_NUMERIC="fi_FI.UTF-8"
LC_TIME="fi_FI.UTF-8"
LC_COLLATE="fi_FI.UTF-8"
LC_MONETARY="fi_FI.UTF-8"
LC_MESSAGES="fi_FI.UTF-8"
LC_PAPER="fi_FI.UTF-8"
LC_NAME="fi_FI.UTF-8"
LC_ADDRESS="fi_FI.UTF-8"
LC_TELEPHONE="fi_FI.UTF-8"
LC_MEASUREMENT="fi_FI.UTF-8"
LC_IDENTIFICATION="fi_FI.UTF-8"
LC_ALL=
```

**Comment by aajanki** [comment]
There indeed was a bug how non-ascii command line parameters were parsed. It's now fixed on the master branch.
