### ISSUE TITLE
Downloading selected Areena audio episodes doesn't work

### ISSUE THREAD

**Issue by lsolin** [aajanki/yle-dl#236]
Areena radio programs side has changed. The episodes don't have their own page url.

`yle-dl https://areena.yle.fi/audio/1-2282921`

downloads only the latest episode.

**Comment by hertell** [comment]
Also other types of radio-recordings do not work anymore like: https://arenan.yle.fi/audio/1-1474943

`yle-dl https://arenan.yle.fi/audio/1-1474943
yle-dl 20200222: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2020 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Traceback (most recent call last):
  File "/usr/local/Cellar/yle-dl/20200222/libexec/bin/yle-dl", line 11, in <module>
    load_entry_point('yle-dl==20200222', 'console_scripts', 'yle-dl')()
  File "/usr/local/Cellar/yle-dl/20200222/libexec/lib/python3.7/site-packages/yledl/yledl.py", line 447, in main
    stream_filters, args.postprocess, args.metadatalang)
  File "/usr/local/Cellar/yle-dl/20200222/libexec/lib/python3.7/site-packages/yledl/yledl.py", line 300, in download
    title_formatter, io.ffprobe())
  File "/usr/local/Cellar/yle-dl/20200222/libexec/lib/python3.7/site-packages/yledl/extractors.py", line 348, in extract
    playlist = self.get_playlist(url)
  File "/usr/local/Cellar/yle-dl/20200222/libexec/lib/python3.7/site-packages/yledl/extractors.py", line 400, in get_playlist
    url, series_id)
  File "/usr/local/Cellar/yle-dl/20200222/libexec/lib/python3.7/site-packages/yledl/extractors.py", line 427, in get_playlist_old_style_url
    html = self.httpclient.download_html_tree(url)
  File "/usr/local/Cellar/yle-dl/20200222/libexec/lib/python3.7/site-packages/yledl/http.py", line 60, in download_html_tree
    return lxml.html.fromstring(page)
  File "/usr/local/Cellar/yle-dl/20200222/libexec/vendor/lib/python3.7/site-packages/lxml/html/__init__.py", line 875, in fromstring
    doc = document_fromstring(html, parser=parser, base_url=base_url, **kw)
  File "/usr/local/Cellar/yle-dl/20200222/libexec/vendor/lib/python3.7/site-packages/lxml/html/__init__.py", line 764, in document_fromstring
    "Document is empty")
lxml.etree.ParserError: Document is empty`

**Comment by aajanki** [comment]
The radio programs should again work with the latest master branch.

Most (all?) of the radio URLs on the Areena web application point to series pages. Yle-dl will download all episodes of the series using those URLs. You can't easily get access to single-episode links after the Areena design changes.

**Comment by lsolin** [comment]
Great, thanks! I just noticed though that you can find the old-style episode urls (even for new episodes) by doing a search in areena. Downloading single episodes with them and yle-dl works fine but the browser redirects you to the new-style areena page.
