### ISSUE TITLE
continue from errors

### ISSUE THREAD

**Issue by gunnar12** [aajanki/yle-dl#239]
running "whole series, paiva tunnissa", windows

Always  crashes, quits at some stage

wld be nice if continued and finally get something done, downloaded

]
ERROR: Can't read from POST https://cdnapisec.kaltura.com/api_v3/service/multire

--

      "objectType": "KalturaMetadataFilter",
      "objectIdEqual": "1_4qfrayjn",
      "metadataObjectTypeEqual": "1"
    },
    "ks": "{1:result:ks}"
  }
]
ERROR: Can't read from POST https://cdnapisec.kaltura.com/api_v3/service/multire
quest
Traceback (most recent call last):
  File "audio\yle-dl-master\yledl\http.py", line 100, in post
    r.raise_for_status()
  File "\AppData\Roaming\Python\Python37\site-packages\requests-2
.19.1-py3.7.egg\requests\models.py", line 939, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: ht
tps://cdnapisec.kaltura.com/api_v3/service/multirequest
Traceback (most recent call last):
  File "P:\ST31Xtra\audio\yle-dl-master\yle-dl-script.py", line 11, in <module>
    load_entry_point('yle-dl==20200419', 'console_scripts', 'yle-dl')()
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\yledl.py", line 448, in main
    stream_filters, args.postprocess, args.metadatalang)
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\yledl.py", line 301, in download
    title_formatter, io.ffprobe())
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\extractors.py", line 350, in extra
ct
    for clipurl in playlist]
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\extractors.py", line 350, in <list
comp>
    for clipurl in playlist]
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\extractors.py", line 578, in extra
ct_clip
    pid, clip_url, title_formatter, ffprobe)
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\extractors.py", line 829, in progr
am_info_for_pid
    playback_context = kapi_client.playback_context(entry_id, pageurl)
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\kaltura.py", line 113, in playback
_context
    referrer, self.http_origin)
  File "P:\ST31Xtra\audio\yle-dl-master\yledl\kaltura.py", line 87, in perform_r
equest
    return r.json()
AttributeError: 'NoneType' object has no attribute 'json'

**Comment by gunnar12** [comment]
return r.json()
AttributeError: 'NoneType' object has no attribute 'json'

--  never return with function  without first checking return value first, esp in Python!


then NoneTypes are everywhere in Python!

**Comment by gunnar12** [comment]
THANKS!
