### ISSUE TITLE
--output-template not working, at least not as expected?

### ISSUE THREAD

**Issue by ExTechOp** [aajanki/yle-dl#248]
When trying to download a whole folder of files from Areena with yle-dl 20200807, I am having serious doubts about how --output-template is supposed to work?

`% yle-dl --output-template "${series}${episode}${title}.mp4" https://areena.yle.fi/1-3882471
`
All output goes to file mp4.mkv, which gets repeatedly downloaded ond overwritten

`% yle-dl --output-template "${series}${episode}${title}.mkv" https://areena.yle.fi/1-3882471
`
Crashes:
```
yle-dl 20200807: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2020 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Traceback (most recent call last):
  File "/home/otto/bin/yle-dl", line 8, in <module>
    sys.exit(main())
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/yledl.py", line 452, in main
    res = execute_action(url, action, io, httpclient, title_formatter,
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/yledl.py", line 298, in execute_action
    return download_clips(clips(), dl, io, stream_filters)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/yledl.py", line 280, in clips
    return extractor.extract(url, stream_filters.latest_only,
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 248, in extract
    return [self.extract_clip(clipurl, title_formatter, ffprobe)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 248, in <listcomp>
    return [self.extract_clip(clipurl, title_formatter, ffprobe)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 501, in extract_clip
    program_info = self.program_info_for_pid(
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 710, in program_info_for_pid
    playback_context = kapi_client.playback_context(entry_id, pageurl)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/kaltura.py", line 111, in playback_context
    response = self.perform_request(
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/kaltura.py", line 86, in perform_request
    r = self.httpclient.post(endpoint, request, extra_headers)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/http.py", line 92, in post
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 503 Server Error: Service Unavailable for url: https://cdnapisec.kaltura.com/api_v3/service/multirequest
```

`% yle-dl --output-template "${series}${episode}${title}" https://areena.yle.fi/tv/ohjelmat/30-2234
`
All output goes to ylevideo.mkv, again repeatedly.

Am I correct in assuming that currently the only option to download more than one file is to download them to the default name as mkv files?

**Comment by aajanki** [comment]
I think your shell is interpreting dollar signs as shell variables and substituting empty strings. Use single quote to stop shell from modifying the content of the string:
```
yle-dl --output-template '${series}${episode}${title}.mp4' https://areena.yle.fi/1-3882471
```

**Comment by ExTechOp** [comment]
Damn, I'm getting really good at opening spurious tickets. Of course you are correct.
