### ISSUE TITLE
Valkoinen peura (vain suorana)

### ISSUE THREAD

**Issue by ExTechOp** [aajanki/yle-dl#251]
Attempt to load the film Valkoinen peura (1952) which was only available for direct viewing on Areena at the time (2020-10-01T13:10) fails both with program URL and /suorat URL:
```
% date
Thu 01 Oct 2020 13:10:02 EEST

% yle-dl https://areena.yle.fi/1-1878958
yle-dl 20200807: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2020 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

ERROR: Unsupported stream: This stream has expired

% yle-dl https://areena.yle.fi/tv/suorat
yle-dl 20200807: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2020 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv3

Traceback (most recent call last):
  File "/home/otto/bin/yle-dl", line 8, in <module>
    sys.exit(main())
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/yledl.py", line 452, in main
    res = execute_action(url, action, io, httpclient, title_formatter,
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/yledl.py", line 298, in execute_action
    return download_clips(clips(), dl, io, stream_filters)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/yledl.py", line 280, in clips
    return extractor.extract(url, stream_filters.latest_only,
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 248, in extract
    return [self.extract_clip(clipurl, title_formatter, ffprobe)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 248, in <listcomp>
    return [self.extract_clip(clipurl, title_formatter, ffprobe)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 501, in extract_clip
    program_info = self.program_info_for_pid(
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 678, in program_info_for_pid
    preview = self.preview_parser(pid, pageurl)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 750, in preview_parser
    preview_json = JSONP.load_json(self.preview_url(pid),
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/extractors.py", line 70, in load_json
    json_string = httpclient.download_page(url, headers)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/http.py", line 45, in download_page
    response = self.get(url, extra_headers)
  File "/home/otto/.local/lib/python3.8/site-packages/yledl/http.py", line 82, in get
    r.raise_for_status()
  File "/usr/lib/python3.8/site-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://player.api.yle.fi/v1/preview/suorat.json?language=fin&ssl=true&countryCode=FI&host=areenaylefi&app_id=player_static_prod&app_key=8930d72170e48303cf5f3867780d549b
```

**Comment by ExTechOp** [comment]
Sigh, I seem to be pestered by issues like this. My initial URL was copy-pasted incorrectly.
