### ISSUE TITLE
importlib.metadata.PackageNotFoundError: yle-dl

### ISSUE THREAD

**Issue by laurifa** [aajanki/yle-dl#260]
```
Traceback (most recent call last):
  File "/usr/bin/yle-dl", line 33, in <module>
    sys.exit(load_entry_point('yle-dl==20201022', 'console_scripts', 'yle-dl')())
  File "/usr/bin/yle-dl", line 22, in importlib_load_entry_point
    for entry_point in distribution(dist_name).entry_points
  File "/usr/lib/python3.9/importlib/metadata.py", line 524, in distribution
    return Distribution.from_name(distribution_name)
  File "/usr/lib/python3.9/importlib/metadata.py", line 187, in from_name
    raise PackageNotFoundError(name)
importlib.metadata.PackageNotFoundError: yle-dl
```
yle-dl 20201022 has stop working on Arch Linux

**Comment by laurifa** [comment]
ok, my bad! For some reason upgrading OS and re-installing yle-dl via AUR fix the problem.

**Comment by aajanki** [comment]
Did you happen to update Python from 3.8 to 3.9? One cause for that kind of error could be that yle-dl package has been installed on one version of Python but not on the default version of Python.

**Comment by laurifa** [comment]
[2020-12-02T16:51:57+0200] [ALPM] upgraded python (3.8.6-1 -> 3.9.0-1)

Yes, that is the case!
