### ISSUE TITLE
Show metadata returns forbidden

### ISSUE THREAD

**Issue by teeppaja** [aajanki/yle-dl#319]
Fetching information of show's episodes returns status code Forbidden (403):

$ yle-dl --showmetadata https://areena.yle.fi/1-50363509
Traceback (most recent call last):
  File "/home/the_user/.local/bin/yle-dl", line 8, in <module>
    sys.exit(main())
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/yledl.py", line 480, in main
    res = execute_action(
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/yledl.py", line 289, in execute_action
    print_enc(json.dumps(dl.get_metadata(clips(), io), indent=2))
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/yledl.py", line 276, in clips
    return extractor.extract(url, stream_filters.latest_only,
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/extractors.py", line 206, in extract
    playlist = self.get_playlist(url, latest_only)
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/extractors.py", line 211, in get_playlist
    return AreenaPlaylistParser(self.httpclient).get(url, latest_only)
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/extractors.py", line 235, in get
    playlist = self._download_playlist(series_id, latest_only, self._playlist_page)
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/extractors.py", line 309, in _download_playlist
    page = get_playlist_page(series_id, ascending, offset, page_size)
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/extractors.py", line 325, in _playlist_page
    playlist = self.httpclient.download_json(pl_url)
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/http.py", line 48, in download_json
    response = self.get(url, extra_headers)
  File "/home/the_user/.local/lib/python3.8/site-packages/yledl/http.py", line 95, in get
    r.raise_for_status()
  File "/usr/lib/python3/dist-packages/requests/models.py", line 940, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://programs.api.yle.fi/v3/schema/v1/series/1-50363509/episodes?availability=current&order=natural%3Aasc&program_type=program&fields=id&offset=0&limit=100&app_id=areena_web_frontend_prod&app_key=4622a8f8505bb056c956832a70c105d4

Using latest version:
$ yle-dl
usage: yle-dl [-h] [-V] [--debug] [-q] [-c FILENAME] [-i FILENAME] [-o FILENAME] [--output-template TEMPLATE] [--pipe]
              [--destdir DIR] [--create-dirs] [--showurl | --showtitle | --showepisodepage | --showmetadata] [--vfat]
              [--no-resume] [--no-overwrite] [--ratelimit BR] [--proxy URI] [--postprocess CMD] [--sublang LANG]
              [--metadatalang LANG] [--latestepisode] [--maxbitrate RATE] [--resolution RES] [--startposition S]
              [--duration S] [--preferformat F] [--backend BE] [--ffmpeg PATH] [--ffprobe PATH] [--wget PATH]
              [url]

yle-dl 20220610: Download media files from Yle Areena and Elävä Arkisto

**Comment by ernie77** [comment]
The Yle API is gone and so are the season numbers. Maybe rollback commit e4487bb.

**Comment by aajanki** [comment]
The master branch contains a partial fix. It lists the episodes again, but they might not be correctly ordered which means that `--latestepisode` might get a wrong episode.

**Comment by aajanki** [comment]
This is now fixed on release 20220704 (including the sort order).
