### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'strip'

### ISSUE THREAD

**Issue by Totapulchra** [aajanki/yle-dl#363]
```
> /home/tp/.venv/yle-dl/bin/yle-dl --showtitle https://areena.yle.fi/1-4141711  
Filmikellari: Filmikellarissa sukellus pinnan alle: E145-2012-04-10T09:28
Filmikellari: ti 17.4.2012: E101-2012-04-17T07:18
Traceback (most recent call last):
  File "/home/tp/.venv/yle-dl/bin/yle-dl", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/yledl.py", line 514, in main
    res = execute_action(
          ^^^^^^^^^^^^^^^
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/yledl.py", line 308, in execute_action
    print_lines(dl.get_titles(url, io, stream_filters.latest_only))
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/yledl.py", line 324, in print_lines
    for line in lines:
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/downloader.py", line 122, in <genexpr>
    return (sane_filename(clip.title or '', io.excludechars) for clip in clips)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/extractors.py", line 245, in <genexpr>
    return (self.extract_clip(clipurl, url) for clipurl in playlist)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/extractors.py", line 707, in extract_clip
    program_info = self.program_info_for_pid(
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/extractors.py", line 913, in program_info_for_pid
    season_and_episode = preview.season_and_episode()
                         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/tp/.venv/yle-dl/lib/python3.11/site-packages/yledl/extractors.py", line 600, in season_and_episode
    desc = TranslationChooser(['fin']).choose_long_form(desc_object).strip()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'strip'
```

**Comment by aajanki** [comment]
Thanks for reporting!

A fix for this issues is now on the master branch. The error happened because yle-dl did not properly handle cases where a description was not available for a video.
