### ISSUE TITLE
Can't download radio programs from Areena

### ISSUE THREAD

**Issue by rhoeden** [aajanki/yle-dl#57]
I can't download radio programs from Areena. No issues with tv programs or material from Elävä Arkisto. The following log concerns this: http://areena.yle.fi/radio/2540958
***
yle-dl 2.5.0: Download media files from Yle Areena and Elävä Arkisto
Copyright (C) 2009-2015 Antti Ajanki <antti.ajanki@iki.fi>, license: GPLv2
Warning: Resume not supported on this stream

                            KSV Adobe HDS Downloader

Processing manifest info....                                                   
Unable to download the manifest                                                
Warning: Resume not supported on this stream
Output file: Työttömyysturva remonttiin-2015-01-29T08:10:00.flv
[download] Downloading f4m manifest
Traceback (most recent call last):
  File "/usr/bin/yle-dl", line 2022, in <module>
    main()
  File "/usr/bin/yle-dl", line 2018, in main
    sys.exit(dl.download_episodes(url, sfilt, rtmpdumpargs, destdir))
  File "/usr/bin/yle-dl", line 1632, in download_episodes
    return self._retry_call('download_episodes', *args, **kwargs)
  File "/usr/bin/yle-dl", line 1621, in _retry_call
    return self._retry_call(method_name, *args, **kwargs)
  File "/usr/bin/yle-dl", line 1619, in _retry_call
    res = method(*args, **kwargs)
  File "/usr/bin/yle-dl", line 376, in download_episodes
    self.OP_DOWNLOAD)
  File "/usr/bin/yle-dl", line 418, in process_episodes
    rtmpdumpargs, destdir, optype)
  File "/usr/bin/yle-dl", line 452, in process_single_episode
    return downloader.save_stream()
  File "/usr/bin/yle-dl", line 1877, in save_stream
    if not f4mdl.download(outputfile, info):
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/common.py", line 314, in download
    return self.real_download(filename, info_dict)
  File "/usr/lib/python2.7/site-packages/youtube_dl/downloader/f4m.py", line 237, in real_download
    manifest = self.ydl.urlopen(man_url).read()
  File "/usr/lib/python2.7/site-packages/youtube_dl/YoutubeDL.py", line 1485, in urlopen
    return self._opener.open(req, timeout=self._socket_timeout)
  File "/usr/lib/python2.7/urllib2.py", line 437, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 550, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 475, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 409, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 558, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 404: Not Found

**Comment by aajanki** [comment]
This problem is already fixed in master.

If you don't want to update, you can also use the `--protocol rtmp` switch: `yle-dl --protocol rtmp http://areena.yle.fi/radio/2540958`
